joint_names:
  ["base_cyl",
  "cyl_arm1",
  "arm1_arm2",
  "arm2_arm3",
  "arm3_tool"]
joint_ranges:
  [[-2.0, 2.0],
  [0.00, 1.60],
  [0.00, -1.60],
  [-1.57, 0.00],
  [-31.4, 31.4]]
joy_ranges:
  [[-1.0, 1.0],
  [-0.1, -1.0],
  [-0.86, -0.16],
  [-0.3, -1.0],
  [1.0, -1.0]]
